### ISSUE TITLE
Samtools faidx: unrecognized option '--fai-idx'

### ISSUE THREAD

**Issue by kp4918** [rki-mf1/clean#114]
**Issue: Unsupported --fai-idx Option in samtools faidx Command**

**Error Summary**
I encountered an issue with the process prepare_contamination:concat_contamination in the pipeline, where the samtools faidx command was called with the unsupported option --fai-idx, leading to an error.

To work around this, I wrote a wrapper in my SLURM script to handle the command without the --fai-idx option. However, this could indicate that there is either a typo in the process prepare_contamination:concat_contamination, or that --fai-idx is no longer supported in recent versions of samtools (I used v1.10).

Would you be able to confirm if this option is intended to be included, or if there's an alternative way to specify the output index for samtools faidx in this pipeline?

**Full Error Details**
The workflow error message is as follows:

```plaintext
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

Error executing process > 'prepare_contamination:concat_contamination'

Caused by:
  Process `prepare_contamination:concat_contamination` terminated with an error exit status (1)

Command executed:
  # Combine input files, rename duplicate sequences (by id) if found, and compress
  seqkit seq dcs.fa.gz eco.fa.gz | seqkit rename | bgzip -@ 1 -c > db.fa.gz
  samtools faidx db.fa.gz --fai-idx db.fa.fai

Command exit status:
  1

Command output:
  (empty)

Command error:
  faidx: unrecognized option '--fai-idx'
  Usage: samtools faidx <file.fa|file.fa.gz> [<reg> [...]]
  Option: 
   -o, --output FILE        Write FASTA to file.
   -n, --length INT         Length of FASTA sequence line. [60]
   -c, --continue           Continue after trying to retrieve missing region.
   -r, --region-file FILE   File of regions.  Format is chr:from-to. One per line.
   -i, --reverse-complement Reverse complement sequences.
       --mark-strand TYPE   Add strand indicator to sequence name
                            TYPE = rc   for /rc on negative strand (default)
                                   no   for no strand indicator
                                   sign for (+) / (-)
                                   custom,<pos>,<neg> for custom indicator
   -f, --fastq              File and index in FASTQ format.
   -h, --help               This message.
```

**Comment by hoelzer** [comment]
Hey @kp4918 to answer your question, we need to know how you executed the pipeline and in which version. Can you please share your `nextflow run` command? Did you use conda or an container engine? 

Also, please try the latest `-r v1.1.1` to be sure you are using the latest code base and dependencies.

**Comment by kp4918** [comment]
> Hey @kp4918 to answer your question, we need to know how you executed the pipeline and in which version. Can you please share your `nextflow run` command? Did you use conda or an container engine?
> 
> Also, please try the latest `-r v1.1.1` to be sure you are using the latest code base and dependencies.

Hi @hoelzer, thanks for your reply. I was using an older version in conda, have replaced with v1.1.1 and problem has resolved. Many thanks!

**Comment by kp4918** [comment]
> Hey @kp4918 to answer your question, we need to know how you executed the pipeline and in which version. Can you please share your `nextflow run` command? Did you use conda or an container engine?
> 
> Also, please try the latest `-r v1.1.1` to be sure you are using the latest code base and dependencies.

Hi @hoelzer, thanks for your reply. I was using an older version in conda, have replaced with v1.1.1 and problem has resolved. Many thanks!
