### ISSUE TITLE
make contig names unique when concatenating

### ISSUE THREAD

**Issue by MarieLataretu** [rki-mf1/clean#44]
problems at samtools

minimap2 seems to have no problems

**Comment by matthuska** [comment]
This could be done by piping the fastq file through `seqkit rename`[1], which will append numbers to any sequences with duplicate names and leave the rest alone. The only challenge is finding a singularity container with seqkit.

[1] https://bioinf.shenwei.me/seqkit/usage/#rename

**Comment by MarieLataretu** [comment]
closed with #81
