### ISSUE TITLE
add a keep option

### ISSUE THREAD

**Issue by MarieLataretu** [rki-mf1/clean#55]
- add a parameter `--keep` to specify fasta(s)
- start another mapping run against the keep fastas
- keep reads that mapped against host/control/contamination AND aginst the keep fastas

What do you think, @hoelzer ?

**Comment by hoelzer** [comment]
In general yes!

But I suggest to map _simultaneously_ against the contamination AND a reference-to-keep if provided. And then always keep reads in the clean bin that mapped against the reference-to-keep. What mapped against contamination is sorted out into the contamination bin.

And unmapped... Unmapped is then also going in the clean bin,right? Just to not lose smt maybe important.

That would be my approach, or do I miss smt?

**Comment by MarieLataretu** [comment]
So you'd concatenate everything, contamination(s) and the reference-to-keep?

Currently, we run minimap2 with `-N5 and --secondary=no`: search for at most 5 secondary alignments (default) and output no secondary alignment. What if the 6th secondary alignment maps to the reference-to-keep? If we map twice we still can follow the strategy to discriminate between mapped and unmapped reads, independent of the mapping location (e.g. when contamination 1, contamination 2 and control)

**Comment by hoelzer** [comment]
Yes, normally I would concatenate everything. The thing is the following scenario:

* you have a virus that you want to decontaminate
* a similar sequence is also integrated into the human genome (EVE)
* you want to keep reads that are human, and remove reads belonging to the virus

Now you map two times like you suggested:

* you get reads mapped to the virus (contamination, you want to sort them out)
* you also get reads mapped to the human genome that you want to keep
    * among them, some of the virus reads are mapping to that EVE, with lower quality, but still they map

Now you keep these reads bc/ they map against your human`--keep` FASTA. But actually, they belong to your contamination (the virus). 

If you would concatenate the human (keep) and virus (contamination) FASTAs then the reads should not map to the human EVE part bc/ they have a better quality when mapping to the virus. At least that's how it should work : )

I think in your approach (mapping multiple times) you would need to take also the mapping quality into account. E.g. if a read A mapped against the human genome (keep) and the virus (contamination) you would still reject that read if the mapping quality against the virus is better.

**Comment by MarieLataretu** [comment]
> Now you keep these reads bc/ they map against your human`--keep` FASTA. But actually, they belong to your contamination (the virus).
> 
> If you would concatenate the human (keep) and virus (contamination) FASTAs then the reads should not map to the human EVE part bc/ they have a better quality when mapping to the virus. At least that's how it should work : )

I see your point. But if the similarity is so high that you can't tell from where the read originates, it's up to the mapper, the order of the references and/or some mapper-specific assumptions where the primary alignment ends up. So you could filter out human reads that could also be virus reads more or less by chance, or?

When mapping twice we could select e.g. the longer alignment and decide to keep it if has the same length.

**Comment by hoelzer** [comment]
Yes, you're totally right. It's still not sure where the read then ends up based on the mapper, prameters, ... 

Yes, mapping two times would then just need some further decision step (e.g. on aln length) to decide what happens w/ reads that map against both the (optional) reference-to-keep and then contamination(s). 

(btw, I think this is really an important thing to include and might come up anyway in a revision. Which also means we could keep it in mind/implement basically but then focus on getting the manuscript into review while finalizing : ) )

**Comment by MarieLataretu** [comment]
closed with #81
