### ISSUE TITLE
Use human GRCh38 T2T genome as new option

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/clean#57]

**Comment by hoelzer** [comment]
Ok, is already default :)

**Comment by selmapichot** [comment]
Hi, is it possible to use the recent T2T reference genome instead of the GRCh38 ? Many thanks

**Comment by hoelzer** [comment]
Hi, thanks for the hint. Indeed, it would be nice to provide this. Do you have a link where one could download the recent T2T human genome FASTA? 

Besides, if you directly want to use it you can download the data yourself and provide it as an `--own` input to CLEAN

**Comment by matthuska** [comment]
I think the main NCBI page for that genome is here: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_009914755.1/

They even provide a URL to download it, using curl, but I haven't tested it out yet:

```
https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/GCF_009914755.1/download?include_annotation_type=GENOME_FASTA&include_annotation_type=GENOME_GFF&include_annotation_type=RNA_FASTA&include_annotation_type=CDS_FASTA&include_annotation_type=PROT_FASTA&include_annotation_type=SEQUENCE_REPORT&hydrated=FULLY_HYDRATED
```

**Comment by hoelzer** [comment]
Is added now in the latest release.
