### ISSUE TITLE
Increase memory when bbduk runs out

### ISSUE THREAD

**Issue by MarieLataretu** [rki-mf1/clean#82]
bbduk can use a lot of memory and that can cause it to fail, especially in a shared computing environment like an HPC. Detect this, and auto increase the amount of memory reserved for the task then rerun the process. Additionally, increase the default memory reservation.

**Comment by MarieLataretu** [comment]
The command exit status of the `bbduk` process is `1`, if it runs out of memory

**Comment by hoelzer** [comment]
#101 fixes this issue with BBDUK
