### ISSUE TITLE
bam files instead of fastq?

### ISSUE THREAD

**Issue by selmapichot** [rki-mf1/clean#88]
Hi, 
On nanopore data, is it possible to use basecalled bam files (basecalled with Dorado) as input sample? (to remove the DCS)
Many thanks,
Selma.

**Comment by hoelzer** [comment]
Hi Selma,

no, this is not a possible input option. But you should be able to easily convert bam 2 fastq. There are tools when you google it

Thx for your interest in the pipeline! I will close the  ticket but please feel free to reopen if you have any further related problems
